FROM gitlab/gitlab-ce:8.7.0-rc3.ce.0
MAINTAINER "H.Chen" <winghc@hotmail.com>


#RUN apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends ldap-client ldap-utils libpam-ldap libnss-ldap nslcd postfix


